services:
  frontend-vue:
    container_name: frontend-vue
    build:
      context: ./theme02
    ports:
      - "8080:8080"
    volumes:
      - ./theme02:/src
      - frontend-node_modules:/src/node_modules
    tty: true
    environment:
      NODE_ENV: development
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  frontend-node_modules:
