name: 🎨 Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'

      - name: 📦 Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: 🛠️ Build project
        working-directory: ./frontend
        run: npm run build
